"""Change user model to telegram login

Revision ID: a7fca30673fb
Revises: e84f693c965b
Create Date: 2024-07-27 19:16:22.339964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7fca30673fb'
down_revision: Union[str, None] = 'e84f693c965b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('threads', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('telegram_id', sa.BigInteger(), nullable=True))
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.drop_column('users', 'email')
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(), nullable=True))
    op.add_column('users', sa.Column('email', sa.VARCHAR(), nullable=True))
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=1)
    op.drop_column('users', 'telegram_id')
    op.drop_column('threads', 'created_at')
    # ### end Alembic commands ###
